name: Build and Scan Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: local/app:latest

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.1

      - name: Scan image with Trivy
        run: |
          trivy image --exit-code 0 --severity HIGH,CRITICAL local/app:latest
          trivy image --exit-code 1 --severity CRITICAL local/app:latest
